version: '3.4'

services:
  productsservice.presentation:
    image: ${DOCKER_REGISTRY}productsservicepresentation
    build:
      context: .
      dockerfile: ProductsService.Presentation/Dockerfile
